### ISSUE TITLE
How can I enable CORS?

### ISSUE THREAD

**Issue by binarykitchen** [AveVlad/gulp-connect#100]
Would be good to see a tip for that. Tried with the middleware https://www.npmjs.com/package/cors but it didn't seem to work ...

**Comment by Latrasis** [comment]
bump

**Comment by mildfuzz** [comment]
No resolution here?

**Comment by mildfuzz** [comment]
install cors package:
````npm install --save-dev cors````

then add it as middleware to connect:

var gulp = require('gulp');
var connect = require('gulp-connect');
var cors = require('cors');

````gulp.task('connect', function() {
  connect.server({
    root: 'app',
    middleware: function() {
        return [cors()];
    }
  });
});````

**Comment by PrimeByDesign** [comment]
Doesn't seem to work for me with: 

    var gulp    		= require('gulp');
    var connect 		= require('gulp-connect');
    var cors               = require('cors');

    gulp.task('connect', function() {
      connect.server({
    
          root: './framework/src/',
          middleware: function() {
              return [cors()];
          },
          port: 1234,
          livereload: true
      });
    });

I'd really appreciate any suggestions.

**Comment by mildfuzz** [comment]
On the face of it, it looks like very little is different that in my example, maybe investigate version numbers?

**Comment by PrimeByDesign** [comment]
Hi John, 

I re-downloaded gulp connect. 

	sudo npm install --save-dev gulp-connect

I also did a sudo npm update 

I then ran with gulp again but it’s still giving me the error. :/

**Comment by PrimeByDesign** [comment]
Just to clarify... if I use your exact example will it add the origin policy header? Do I have to do anything else for this?

**Comment by mildfuzz** [comment]
I presume the error you mean is in browser? or another error?

I did nothing but the steps listed

**Comment by PrimeByDesign** [comment]
Yea, in the chrome developer tools:

This is the error: 

XMLHttpRequest cannot load http://localhost:5000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1234' is therefore not allowed access. The response had HTTP status code 405.

livereload.js?snipver=1:193 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by mildfuzz** [comment]
Clutching at straws here, as I'm not a developer on the project, just someone who found a workaround.

You also have a livereload error, tried turning that off?

**Comment by PrimeByDesign** [comment]
No luck, 

gulp.task('connect', function() {
  connect.server({

      root: './framework/src/',
      middleware: function() {
          return [cors()];
      }
  });
});

I wonder… Do I have to enable something on my service to allow cross origins? 

XMLHttpRequest cannot load http://localhost:5000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1234' is therefore not allowed access. The response had HTTP status code 405.

**Comment by mildfuzz** [comment]
Should just be the server that needs to have CORS headers set. Possibly worth stripping back your project to the bare essentials to isolate the issue?




What happens if you serve the same folder with the http-server package with cors flag enabled?


John Farrow

**Comment by PrimeByDesign** [comment]
Hi John…

Sorry can you specify which Http Server package your referring to? I’m not sure what it’s called?

**Comment by PrimeByDesign** [comment]
Do you mean gulp-webserver?

**Comment by mildfuzz** [comment]
This puppy -> https://www.npmjs.com/package/http-server


Just a quick and dirty static file server


John Farrow

**Comment by PrimeByDesign** [comment]
John, 

Thank you so much for all of your help today. You’ve been an absolute star. 

I think I was just getting a little confused as I’m new to this stuff. It turns out when inspecting the packets I could see that the CORS headers were present. 

Upon further investigation I realised that I needed to enable to headers in my API back end and not in the front end part of the system. I’ve made the changes and now I am getting id is undefined errors which seem a little more familiar. 

So at the moment I think my problem may be solved. 

Thank you again.

**Comment by mildfuzz** [comment]
Ha, I did think that, but didn’t want to patronise! Glad you sorted it out!


John Farrow

**Comment by PrimeByDesign** [comment]
Ah well not quite… I always celebrate too early! 

Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

**Comment by KaoruDev** [comment]
figured out how to use setup the middleware using `gulp-connect`

```javascript
var gulp = require('gulp');
var connect = require('gulp-connect');

var cors = function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', '*');
  next();
};

gulp.task('server:test', function () {
  connect.server({
    root: 'dist',
    livereload: true,
    port: 9000,
    middleware: function () {
      return [cors];
    }
  });
});
```

**Comment by binarykitchen** [comment]
@KaoruDev nope, your example didn't work for me. the cors() middleware is never callede on my side. weird ...

**Comment by caleuanhopkins** [comment]
@KaoruDev exampled work for me thanks! +1

@binarykitchen have you ensured you've installed the module with: `npm install --save-dev cors` ?

**Comment by binarykitchen** [comment]
@caleuanhopkins yep

**Comment by cyberwombat** [comment]
@KaoruDev `Access-Control-Allow-Headers` [doesn't allow](https://developer.mozilla.org/En/HTTP_access_control#Access-Control-Allow-Headers) a wildcard so you have to something like:

    res.setHeader('Access-Control-Allow-Headers',  'X-Requested-With, Authorization, ...');

**Comment by KaoruDev** [comment]
@cyberwombat 👍  I've updated my comment to reflect your correction thanks!
