### ISSUE TITLE
Middleware for redirect() and sendFile()

### ISSUE THREAD

**Issue by binarykitchen** [AveVlad/gulp-connect#106]
What connect middleware would you pick for having these two functions? I need these for a special case. I know they exist within ExpressJS but not here.

Any suggestions? I've been searching everywhere and in many npm modules but haven't found anything really good. So I thought why not ask this here?

**Comment by david-gang** [comment]
For redirect i would use https://www.npmjs.com/package/connect-redirection

**Comment by binarykitchen** [comment]
thanks but that package is pretty old ...
