### ISSUE TITLE
log all requests done with gulp-connect

### ISSUE THREAD

**Issue by david-gang** [AveVlad/gulp-connect#107]
This is a cross posting from https://stackoverflow.com/questions/28879379/log-all-requests-done-with-gulp-connect

I use gulp-connect with proxy-middleware.
```javascript
var proxy_function = function(connect, o) {
    return [

        ,(function() {
        var url = require('url');
        var proxy = require('proxy-middleware');
        var options = url.parse(a);
        options.route = b;
        return proxy(options);
    })() ];
};

gulp.task('connect', function() {
    connect.server({
        port: '8002',
        root: build_dest,
        middleware: proxy_function
    });
});
```
There is something with the proxy function which does not work out so i want to log the actual request done by the proxy.

How can i accomplish this?

There is a logging framework caled morgan, which would be nice to use, but i don't know how somehow to inject it into gulp-connect

**Comment by david-gang** [comment]
Hi @AveVlad,

May you please explain why this issue was closed?
Should i use connect directly, or is there a way to solve this issue with gulp-connect ?

Thanks,
David

**Comment by AveVlad** [comment]
Hi @david-gang use http://www.browsersync.io/  :smiley:

**Comment by david-gang** [comment]
thanks for your quick reply :-)
