### ISSUE TITLE
Fallback is not working correctly

### ISSUE THREAD

**Issue by slavafomin** [AveVlad/gulp-connect#114]
Hello!

I've tried to use fallback feature today, but it looks like it's broken.

First, I've tried to use the following configuration:

```javascript
gulp.task('webserver', function () {
  connect.server({
    root: './build',
    port: 8888,
    fallback: 'index.html'
  });
});
```

Gulp crashes with the following error:

```text
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'index.html'
```

When I set `fallback` to the path relative to the project root (instead of server root) i.e.: `fallback: './build/index.html'`, I'm getting the result, but it's formated as `text/plain` not as `text/html`. Looks like response's `Content-Type` header is missing (as well as other headers which normally presents).

**Comment by slavafomin** [comment]
I wasn't being able to find any working Node web server to use with my single page application, so I've created a simple node server of my own on top of Connect and server-static. Maybe it will help someone: https://github.com/betsol/spa-server. Cheers!

**Comment by siawyoung** [comment]
Was there any resolution to this issue? I'm facing the same issue too.

**Comment by bc-jasond** [comment]
same here

**Comment by vangorra** [comment]
I found setting the path to fallback to an absolute path works great.

``` javascript
  connect.server({
    root: path.resolve(path.join(__dirname, 'dist/app')),
    livereload: false,
    host: '0.0.0.0',
    port: 8000,
    fallback: path.resolve('./dist/app/index.html')
  });
```
