### ISSUE TITLE
Livereload in Multiserver

### ISSUE THREAD

**Issue by eugene-d** [AveVlad/gulp-connect#116]
Hi there,
I try to use multiserver config from your example and have a trouble with livereload. When I set option "livereload" to false value in one server and true to another, both the servers starts with livereload. Then livereload doesn't work because two servers use it (as I know it should be only one active). Log message also shows that both the servers start on the same port 8000, not 8000 and 8001, actually they work on different ports.

https://www.dropbox.com/s/0e2ks4mgksx8brl/Screenshot%202015-04-03%2010.52.23.png?dl=0

**Comment by euge** [comment]
Having the same exact issue

**Comment by fer** [comment]
I just noticed that this option expects an object as an input:

```
livereload: {enable: true, port: 1234}
```

**Comment by pavelsof** [comment]
+1

**Comment by amant** [comment]
Seems like variable `lr` and `opt`, are being shared across multiple instances of servers, which I suspect is the cause of this issue.
+1

**Comment by justinmchase** [comment]
Some multi-server bugs have been fixed since this was opened, please try again and let me know if you have any issues!

**Comment by itstrive** [comment]
Same problem, `gulp-connect` version is 5.6.1 ,  multi-server can't reload for me.
