### ISSUE TITLE
connect.reload is reloading entire page when writing sourcemaps to file

### ISSUE THREAD

**Issue by mwq27** [AveVlad/gulp-connect#117]
Here's my gulp task for SCSS:

```
return gulp
        .src(config.appDir + '/**/*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass({includePaths: config.sass.includePaths}))
        .pipe(sourcemaps.write('./')) //defaults to inline source maps.
        .pipe(gulp.dest(config.tmpDir + '/resources/css'))
        .pipe($.connect.reload());
```
When I specify a relative path in the ```sourcemaps.write()``` call, it's making the page reload.  If I don't put a relative path, it defaults to inline sourcemaps, and just injects the CSS like it should, without a page reload.  Is this a bug with gulp-connect?  Or is there something that i'm missing?

THanks

**Comment by mbme** [comment]
@mwq27 it happens because of source maps http://www.browsersync.io/docs/gulp/#gulp-sass-maps

**Comment by justinmchase** [comment]
Closing for age. If this is still a problem for you please re-open. PR's welcome.
