### ISSUE TITLE
no response when i add a background image

### ISSUE THREAD

**Issue by qianjiahao** [AveVlad/gulp-connect#118]
i am using gulp-connect and actually i nice to develop the browse project .

my issue is when i add a new image file and load it into css , the gulp-connect will not show the result in the browse , and i use the chrome and find the image url has been already loaded in the code , and i confuse , how should i figure it out ?

**Comment by AveVlad** [comment]
gulp watch

**Comment by qianjiahao** [comment]
my images contained in public directory ,and my code like :
      gulp.task('connect', function() {
	connect.server({
		root: './',
		livereload: true
	});
    });

    gulp.task('public', function() {

	gulp.src('public/**')
		.pipe(connect.reload());
    });

    gulp.task('watch', function() {

	gulp.watch('public/**', ['public']);

	gulp.watch('public/controller/*.js', ['scripts']);
    });

    gulp.task('default', ['connect', 'watch']);

i config the whole public directory to watch ... i don't know why image can't load into the borwser

**Comment by fmsf** [comment]
@AveVlad having the same issue. Having an image at `/dist/img/foo.png`, if I put the url on the browser it works properly. But if I try to link it from `<img src="/img/foo.png">` or from a css property it will hang that request. (I am on 2.2.0)

**Comment by Sedushi** [comment]
I'm having the same issue. Hitting an image directly in the browser will work but loading it through html or css will cause an endless image load with the status of `(pending)`.

I'm running on Chrome 42.0.2311.135. It works in FireFox so that may suggest it's something wrong with Chrome and not `gulp-connect`.

![selection_004](https://cloud.githubusercontent.com/assets/2263978/7522646/dd65a8ee-f4b3-11e4-9b78-0c430368c832.png)
![selection_005](https://cloud.githubusercontent.com/assets/2263978/7522648/df5e6a78-f4b3-11e4-927a-8b819ea4950a.png)

**Comment by ksr583** [comment]
Having this same issue on a project. It's very annoying.

**Comment by killswitch** [comment]
Working with @ksr583 and we've ran into this issue using `gulp-connect` and swapped out for `browser-sync` and are getting the same issue, I think this is an actual bug in `connect`

**Comment by thebillkidy** [comment]
I have the same problem, this should really get resolved.

**Comment by wvankuipers** [comment]
:+1: I have the same issue

**Comment by jacksonhyde** [comment]
:+1: getting exactly the same thing using `browser-sync 2.10.0` (which has `connect ^3.4.0` as a dependency).

**Comment by bluesliverx** [comment]
+1 same issue

**Comment by bluesliverx** [comment]
Appears to be a chrome bug: https://code.google.com/p/chromium/issues/detail?id=490027

Restarting the tab (closing it and navigating to the page again) works for a little bit.

**Comment by justinmchase** [comment]
Is anyone still hitting this? Closing due to age, please re-open if you're still hitting it, PR's welcome.
