### ISSUE TITLE
Task never finishes with gulp v4.0

### ISSUE THREAD

**Issue by lzrski** [AveVlad/gulp-connect#122]
With gulp v4.0 task like this never finishes:

```coffee-script
gulp.task 'serve', ->
  connect.server
    root: './dist'
    port: 8001
    livereload: true
```

I had to add done callback and call it "manually" like that:

```coffee-script
gulp.task 'serve', (done) ->
  connect.server
    root: './dist'
    port: 8001
    livereload: true

  do done
```

It doesn't feel right. The server is really started after the task finishes and error handling is lost.

Am I doing something wrong or is this an issue in gulp-connect?

**Comment by acierto** [comment]
thanks for the tip how to fix it, I experience the same problem with gulp 3.9.0. I noticed that it happens only when livereload is true

**Comment by justinmchase** [comment]
You have to stop the server, these api's have been fixed since this bug was opened.
