### ISSUE TITLE
liveeload execute twice 

### ISSUE THREAD

**Issue by sirzxj** [AveVlad/gulp-connect#123]
when I save the html file，my browser execute twice，anybody have the same question ?
```
var gulp = require('gulp'),
	connect = require('gulp-connect');

gulp.task('connect', function() {
	connect.server({
		root:['demo'],
		port: 8008,
		livereload: true
	})
});
gulp.task('html', function() {
	gulp.src('**/*.html')
		.pipe(connect.reload());
});
gulp.task('watch', function() {
	gulp.watch(['**/*.html'], ['html']);
});

gulp.task('default', ['connect','watch']);
```

**Comment by Mangor** [comment]
+

**Comment by red2678** [comment]
+1

**Comment by ykyuen** [comment]
+1

**Comment by almeidap** [comment]
This issue is still present on the latest version (2.3.1). Any updates for a possible fix? Thanks!

**Comment by guillermo-varela** [comment]
Hi guys!

I found out that using [gulp-watch](https://www.npmjs.com/package/gulp-watch) the resources are loaded only once, as they should.

```javascript
var gulp = require('gulp'),
    connect = require('gulp-connect'),
    watch = require('gulp-watch');

gulp.task('connect', function() {
    connect.server({
        root:['demo'],
        port: 8008,
        livereload: true
    })
});

gulp.task('watch', function() {
    gulp.watch(['**/*.html'], ['html']);
    watch('**/*.html').pipe(connect.reload());
});

gulp.task('default', ['connect','watch']);
```

I don't know where the error is when using gulp.watch, but this might help as a workaround in the meantime :smile:

**Comment by kmturley** [comment]
I think it could be because gulp.watch now fires the callback for each file discovered (see example):
https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb

    gulp.watch('js/**/*.js', function(event) {
        console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });

So I guess a better way to write the watch statement + connect.reload would actually be:

    var gulp = require('gulp'),
        connect = require('gulp-connect');

    gulp.task('connect', function() {
        connect.server({
            root:['demo'],
            port: 8008,
            livereload: true
        })
    });

    gulp.task('watch', function() {
        gulp.watch(['**/*.html'], function(event) {
            gulp.src(event.path)
                .pipe(connect.reload());
        });
    });

    gulp.task('default', ['connect','watch']);

**Comment by justinmchase** [comment]
There was a bug here fixed recently, can you all try this again and let me know if you're still having issues?

**Comment by kmturley** [comment]
seems better for me!
