### ISSUE TITLE
Option open does not work with gulp connect v 2.*

### ISSUE THREAD

**Issue by Itagiba** [AveVlad/gulp-connect#126]
Hi I need my webserver function to open index into a new browser window. I have tried to run the following script

gulp.task('webserver', function(){
 console.log("Connecting to live server on port " + varPort);
 connect.server({
	livereload:true,
	port: varPort,
	root: 'app',
	  open: {
		file: 'index.html',
		browser: 'chrome' // if not working OS X browser: 'Google Chrome'
	  }
 });

});

But I am getting this warning:
"Option open does not work with gulp connect v 2.* please read readme.rd" on your repo. I a cannot find any resources on this topic, can you please point me to a workaround?

Thanks

**Comment by thomsta** [comment]
+1

**Comment by kbiesbrock** [comment]
#69 mentions the rationale and a work-around. I arrived here from Google, so I thought I'd point others to the solution.

**Comment by justinmchase** [comment]
Try using [gulp-open](https://www.npmjs.com/package/gulp-open).

**Comment by nunof07** [comment]
For anyone wondering you can install [gulp-open](https://www.npmjs.com/package/gulp-open) and use something similar to this:

```javascript
gulp.task('server', function () {
    var server = connect.server({
        root: 'app',
        livereload: true
    });

    return gulp.src('./')
        .pipe(open({
            uri: 'http://' + server.host + ':' + server.port
        }));
});
```
