### ISSUE TITLE
Ability to actually run server on start

### ISSUE THREAD

**Issue by forforeach** [AveVlad/gulp-connect#128]
Hi, is it possible to add option to run a server in a default browser? Say, by adding 
```javascript
option.run: true
```
or as a task
```javascript
connect.run()
```

Thanks

**Comment by robertbaker** [comment]
+1

**Comment by forforeach** [comment]
Exactly, I do the same and will be happy to have it built-in.

**Comment by mprentic-harris** [comment]
:+1:

**Comment by justinmchase** [comment]
If you send a PR I will merge it.
