### ISSUE TITLE
gulp-connect with php postgresql function enabled

### ISSUE THREAD

**Issue by fbmfbm** [AveVlad/gulp-connect#130]
Hi all,

I'm looking to use gulp-connect one some php sites with postgresql functions enabled, and as i get some "Call to undefined function pg_connect()" it seam that is not the case in gulp-connect.
I'm facing with "Call to undefined function pg_connect()" and i as read in phpinfo() return, the pgsql function is not active...
Is there a way to do that with gulp-connect ???

Than'kx for your help.

**Comment by nkt** [comment]
Are you kidding? gulp-connect couldn't resolve PHP specific problems. Actually it's not resolve anything except serving static files.

**Comment by fbmfbm** [comment]
Hum, for me, it can resolve mysql query as it embed the mysql library.  i  hope we can embed the php_pgsql.dll to.

**Comment by AveVlad** [comment]
kek

**Comment by AveVlad** [comment]
![](http://40.media.tumblr.com/5f34aed1787ad88bcb80edcae178b95c/tumblr_ngriz6Fnjy1tkvf3ho1_1280.jpg)
