### ISSUE TITLE
Move closure variables to ConnectApp object

### ISSUE THREAD

**Issue by robinwassen** [AveVlad/gulp-connect#133]
Currently the `opt`, `lr` and `server` variables are shared between different instances of ConnectApp. This causes some side effect when you for example run two instances of Connect in parallell in gulp.

These three variables should be moved into the ConnectApp object instead of being in the closure.

One example of a side effect is when we bind one connect to port 8080 and one to 9000, the "Server has started..." print will display the settings of the last Connect that we instantiate.

![screen shot 2015-07-01 at 16 00 20](https://cloud.githubusercontent.com/assets/302151/8456302/dfbda7c2-200a-11e5-94a5-e1fc1da97e7b.png)

It still seems to work as intended though.

**Comment by justinmchase** [comment]
There have been some changes in this area, can you try again and see if it works better for you now?
