### ISSUE TITLE
Is this repository deprecated?

### ISSUE THREAD

**Issue by nitzsche9** [AveVlad/gulp-connect#134]
:angry:

**Comment by trakout** [comment]
:thumbsup:

**Comment by MarkHerhold** [comment]
Looks pretty dead. How about it @nkt?

**Comment by nkt** [comment]
I'm not owner of this repository. You should ask @AveVlad about it.

**Comment by justinmchase** [comment]
Version 2.3.0 released: https://github.com/AveVlad/gulp-connect/releases/tag/2.3.0
