### ISSUE TITLE
Creating Virtual Directory (Folder) with Middleware

### ISSUE THREAD

**Issue by atwright147** [AveVlad/gulp-connect#136]
Hi,

I have been trying for the past week to create a virtual directory in my Gulp build script using Connect.

This is the code I have so far but it doesn't seem to work:

```js
// Server and LiveReload
gulp.task('connect', function(){
	// Start Server
	connect.server({
		// Configure port
		port: 8888,
		// Turn on livereload
		livereload: true,
		middleware: function(connect, o) {
			var stubbyProxy = function() {
				var url = require('url');
				var proxy = require('proxy-middleware');
				var options = url.parse('http://localhost:8882/');
				options.route = '/api';
				return proxy(options);
			};
			var virtualFolder = function() {
				return connect().use(
					'/oas',
					connect.static('.')
				);
			};

			return [stubbyProxy, virtualFolder];
		}
	});
});
```

The `stubbyProxy` middleware works but `virtualFolder` does not. I see no feedback in the console but browsing to `http://localhost:8888/oas/` never resolves.

Please help...

**Comment by justinmchase** [comment]
Can you try again, there was a fix to middleware that just went in.

**Comment by justinmchase** [comment]
Please re-open if you are still having issues!

**Comment by IEfucker** [comment]
This code doesnot work for me. Could you tell me how you solved this. And where is connect.use&connect.static document
