### ISSUE TITLE
Dot in a path leads to "Cannot GET"

### ISSUE THREAD

**Issue by ghost** [AveVlad/gulp-connect#139]
Hi,

On paths containing a "dot", gulp-connect breaks with "Cannot GET".

My config:
```javascript
    gulp.task('webserver', function() {
        connect.server({
            port: 80,
            host: 'mysite.lo',
            livereload: true,
            middleware: function() {
                return [ history() ];
            }
        });
    });
```

Thanks,
D.

**Comment by justinmchase** [comment]
What is the full error text? Why not set `host: 'localhost'`?

**Comment by justinmchase** [comment]
Can you try again, there have been some fixes to middleware recently. Re-open this if you're still having trouble, thanks.
