### ISSUE TITLE
serverClose() does not work for multiple servers.

### ISSUE THREAD

**Issue by joshuarh** [AveVlad/gulp-connect#141]
I have a situation in which I am starting multiple servers within the scope of a single task. I would like them all to stop running when my task is complete. For instance:

```
gulp = requrie 'gulp'
connect = require 'gulp-connect'
run = require 'gulp-run'

gulp.task "run-command-that-requires-servers", ->
  connect.server root: 'foo', port: 9999
  connect.server root: 'bar', port: 9998

  run('sleep 1').exec()
    .on 'end', ->
      connect.serverClose()
```

However, `connect.serverClose()` will only stop the most recently created server while all the others continue running.

Is there a supported way to close multiple servers at once? Or at least to get a hold of each server created by `gulp-connect` so I can close them each manually?

**Comment by justinmchase** [comment]
:+1:

**Comment by justinmchase** [comment]
It looks like the `connect.server` function returns a server instance which has a close function on it. FYI.

In my opinion this module should keep an array of each server instead of just the latest server and the various module level functions should operate on each server instead of just the last one.

**Comment by justinmchase** [comment]
Actually this isn't true, the close function is not exposed onto the ConnectApp instance for some reason. 

The current server is a singleton and is privately scoped and cannot be captured externally to close manually, this is blocking bug for me.

**Comment by justinmchase** [comment]
As a workaround, this is hacky as hell but works for me:
```
var https = require('https');
var http = require('http');

var _httpCreateServer = http.createServer;
var _httpsCreateServer = https.createServer;

var servers = [];

http.createServer = function () {

    var server = _httpCreateServer.apply(this, arguments);
    servers.push(server);
    return server;

};

https.createServer = function () {

    var server = _httpsCreateServer.apply(this, arguments);
    servers.push(server);
    return server;

};
```
