### ISSUE TITLE
can not create multiple servers

### ISSUE THREAD

**Issue by laintin** [AveVlad/gulp-connect#142]
i try to search a answer [Issues 40](https://github.com/AveVlad/gulp-connect/issues/40)
but i still can not resolve this.

```javascript
    connect.server({
        port: 9000,
        root: './app',
        livereload: true
    })

    connect.server({
        port: 9100,
        root: "./build"
    })
```

run the above code give me to the same port:
```
[00:06:04] Server started http://localhost:9100
[00:06:04] Server started http://localhost:9100
```

**Comment by laintin** [comment]
<img width="698" alt="screen shot 2015-09-24 at 11 21 01 am" src="https://cloud.githubusercontent.com/assets/3026595/10064746/7c622afe-62ae-11e5-8695-8087a0e5f452.png">

opt variable should be private?

**Comment by justqyx** [comment]
I have met this same problem, @laintin could you tell me how you resolve?

**Comment by laintin** [comment]
@justqyx, you can temporary use `npm install --save-dev gulp-connect-aster`
