### ISSUE TITLE
Multiple servers and livereload not working

### ISSUE THREAD

**Issue by MystK** [AveVlad/gulp-connect#146]
I have two connect servers, but connect.reload() doesn't reload any. Is anyone else have this problem?

**Comment by jasonholloway** [comment]
Me too!

**Comment by justinmchase** [comment]
Can you try again, there were some fixes that just win in for this?

**Comment by justinmchase** [comment]
Please re-open if you're still encountering the issue. PR's welcome.

**Comment by bancuadrian** [comment]
Same problem here. I have two servers open at the same time, but connect.reload() works only for the second one

**Comment by cn-zx** [comment]
> 这里同样的问题。我有两个服务器同时打开，但是connect.reload（）仅适用于第二个服务器

I also encountered it, is there a solution?
