### ISSUE TITLE
https log fix not present in index.js

### ISSUE THREAD

**Issue by mousetree** [AveVlad/gulp-connect#147]
Using the latest `2.2.0` release, the [fix to show `https`in the console output](https://github.com/AveVlad/gulp-connect/commit/a2d1849227dc2ac7f1fd7ce13190ed5e0219841e) is included . It appears in the [src/index.coffee](https://github.com/AveVlad/gulp-connect/blob/master/src/index.coffee#L42):

```
@log "Server started http#{if opt.https? then 's' else ''}://#{opt.host}:#{opt.port}"
```

However, for some reason I can't comprehend, the compiled `index.js` does not include this change. If running this manually by `coffee -o . -bc src/` does not produce the desired result. Instead we're left with:

```
_this.log("Server started http://" + opt.host + ":" + opt.port);
```

**Comment by justinmchase** [comment]
Try the latest version, it could have been the exact version you got, coffee wasn't properly run after merging the fix. This is in the code just published:

```
_this.log("Server started http" + (_this.https != null ? 's' : '') + "://" + _this.host + ":" + _this.port);
```
