### ISSUE TITLE
LiveReload not working

### ISSUE THREAD

**Issue by Snorlock** [AveVlad/gulp-connect#153]
Is there any reason why live reload doesnt work on this code? I cant seem to get it work unfortunaltey. I use babel 6, preset es2015

``` javascript
import gulp from 'gulp';
import babelify from 'babelify';
import connect from 'gulp-connect';
import browserify from 'browserify';
import source from 'vinyl-source-stream';
import sass from 'gulp-sass'

gulp.task('babelify', () => {
    return browserify({
        entries: './js/app.jsx',
        extensions: ['.jsx'],
        debug: true
    })
    .transform(babelify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('public'));
});

gulp.task('connect', () => {

  connect.server({
    root: __dirname+'/public/',
    port: process.env.PORT || 8080,
    livereload: true
  });
});

gulp.task('sass', function () {
  return gulp.src('./sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./public/css'));
});

gulp.task('reload-js', ['babelify'], () => {
    return gulp.src('./public/bundle.js').pipe(connect.reload());
});
gulp.task('reload-html', () => {
    console.log(gulp.src('./public/index.html'))
    return gulp.src('./public/index.html').pipe(connect.reload());
});
gulp.task('reload-css', ['sass'], () => {
    return gulp.src('./public/css/*.css').pipe(connect.reload());
});

gulp.task('watch', () => {
    gulp.watch(['./js/**/*.jsx'], ['reload-js']);
    gulp.watch(['./sass/**/*.scss'], ['reload-css']);
    gulp.watch(['./public/index.html'], ['reload-html'])
})

gulp.task('serve', ['babelify', 'watch', 'connect']);
gulp.task('build', ['babelify']);
```

**Comment by abjrcode** [comment]
I have the same problem with this simple code taken from Cory House's Pluralsight course:

```
"use strict";

var gulp = require('gulp');
var connect = require('gulp-connect'); // Runs a local web server
var open = require('gulp-open'); // Open a URL in a web browser

var config = {
	port: 9005,
	devBaseUrl: 'http://localhost',
	paths: {
		html: './src/*.html',
		dist: './dist'
	}
}

// Start a local development server
gulp.task('connect', function() {
	connect.server({
		root: ['dist'],
		port: config.port,
		base: config.devBaseUrl,
		livereload: true,
		debug: true
	});
});

gulp.task('open', ['connect'], function() {
	gulp.src('dist/index.html')
		.pipe(open('', { url: config.devBaseUrl + ':' + config.port + '/' }));
});

gulp.task('html', function() {
	gulp.src(config.paths.html)
		.pipe(gulp.dest(config.paths.dist))
		.pipe(connect.reload());
});

gulp.task('watch', function() {
	gulp.watch(config.paths.html, ['html']);
});

gulp.task('default', ['html', 'open', 'watch']);
```

**Comment by ttrunck** [comment]
It seems to be the same issue than here: https://github.com/stevelacy/gulp-open/issues/25#issuecomment-167934021

**Comment by abjrcode** [comment]
@ttrunck Unfortunately even after changing to URI nothing seems to happen !

**Comment by shuaibird** [comment]
Doesn't work for me when I change the html or css, only works when I change the js flies

**Comment by jspizziri** [comment]
+1 livereload isn't working for me either. Files are being recompiled, but I have to restart the server in order for them to change.

**Comment by shuaibird** [comment]
Guys, I work it out by myself finally , try my example if you still get stuck.
For simplicity, I create a new dir tree below, make sure installing the gulp, gulp-conncect and  gulp-util (gulp-util is necessary though not to be required in the gulpfile.js in this demo project) modules before move on:
```
|--project
    |-- app
        |-- index.html
        |-- css
            |-- style.css
        |-- js
            |-- script.js
    |-- gulpfile.js
    |-- node_modules
        |-- gulp
        |-- gulp-util
        |-- gulp-connect
    |-- package.json

```
And here comes my gulpfile.js
```javascript
//node modules
var gulp = require('gulp');
var connect = require('gulp-connect');

//sources watched for livereload
var htmlSources =['app/*.html'];
var cssSources = ['app/css/*.css'];
var jsSources = ['app/js/*.js'];
var jsonSources = ['app/js/*.json'];
var allSources = htmlSources.concat(cssSources).concat(jsSources).concat(jsonSources);

//local-server
gulp.task('server', function() {
  connect.server({
    root: 'app',
    livereload: true
  });
});

//livereload
gulp.task('livereload', function() {
  gulp.src(allSources)
    .pipe(connect.reload());
});

//watch the file changes to trigger livereload
gulp.task('watch', function() {
  gulp.watch(allSources, ['livereload']);
});

//gulp default
gulp.task('default', ['server', 'livereoload', 'watch']);
```
Type `gulp` in the CLI and it should work now.

**Comment by mcescalante** [comment]
I am also having issues with livereload working, noticably so since I upgraded `gulp` to 3.9.1. Going to revert to 3.9 tonight to see if the version change in `gulp` is causing issues.

**Comment by justinmchase** [comment]
This should be fixed, please re-open if you're still having problems.

**Comment by pangdaxing23** [comment]
I don't think this is fixed yet. Here is my code:
`"use strict";

var gulp = require("gulp");
var connect = require("gulp-connect"); // runs local dev server
var open = require("gulp-open"); // opens url in browser

var config = {
  port: 9007,
  devBaseUrl: "http://localhost",
  paths: {
    html: "./src/*.html",
    dist: "./dist"
  }
};

// start local dev server
gulp.task("connect", function() {
  connect.server({
    root: "dist",
    port: config.port,
    base: config.devBaseUrl,
    livereload: true
  })
});

gulp.task("open", ["connect"], function() {
  gulp.src("dist/index.html")
      .pipe(open("", { uri: config.devBaseUrl + ":" + config.port + "/" }));
});

gulp.task("html", function() {
  gulp.src(config.paths.html)
      .pipe(gulp.dest(config.paths.dist));
      // .pipe(connect.reload());
});

gulp.task('watch', function() {
  gulp.watch(config.paths.html, ["livereload"]);
});

gulp.task("livereload", function() {
  gulp.src(config.paths.html)
      .pipe(connect.reload());
})

gulp.task("default", ["html", "open", "watch"]);
`

**Comment by henryzp** [comment]
@shuaibird ，are you mac pro or windows？

in my computer，use your code，cannot reload when i change some file。

**Comment by henryzp** [comment]
@justinmchase 

i use [fis](fis.baidu.com)，it can reload page。 but gulp-connect cannot。I'm toke two hours to search method，but also cannot。。。

**Comment by JohnBinder** [comment]
There are times, for reasons unknown to myself, where the script that enables reloading in the html file does not get generated. Putting it in manually at the end of the body may solve your problem.

<script src="//localhost:35729/livereload.js?snipver=1" async="" defer=""></script>

Hope this helps!

**Comment by asierba** [comment]
I was having a similar issue.
After a while I realised that somehow I was missing the livereload.js script in my html page.
I added manually as https://github.com/AveVlad/gulp-connect/issues/153#issuecomment-268644015 and it worked.

But actually, the real problem was that my html page didn't have a proper html format. I didn't even have the html tags on it - just a a file with text. So I guess that's why the html wasn't inserted in the page - the scripts gets inserted just before the closing </html> tag! Silly me..

**Comment by guillermoarturovillagomez** [comment]
First create the server and then apply the watchers, it works for me :)

**Comment by saurabhpati** [comment]
@abjrcode I guess I can help with your issue if it is not awfully late.

replace your 'open' task with 

gulp.task('open', ['connect'], function() {
    gulp.src('dist/index.html')
        .pipe(open({ uri: config.devBaseUrl + ':' + config.port + '/' }));
});
 
I just changed 'url' to 'uri' and removed the '' as the first paramater you passed in open function.

**Comment by adenekan41** [comment]
Did you forget to signal async completion? 

if you did here is what will work for you 

gulp.task('message', async () => {
  await console.log("HTTP Server Started");
});

call async functions on all your gulp tasks that way if one is not done the other would pause
