### ISSUE TITLE
Setting up middleware file "app.js" instead of index.html via gulp-connect

### ISSUE THREAD

**Issue by vbabaria** [AveVlad/gulp-connect#154]
sorry for a newbie question abt gulp-connect, is there a way to setup default entry point to app.js instead of index.html using gulp-connect and livereload

below code works for index.html in "builds/development” directory but i need to setup middlerware (“app.js”) for routing - would really appreciate any pointers - thanks

var connect = require('gulp-connect’); 
gulp.task('connect', function() {
  connect.server({
    root: ‘builds/development',
    livereload: true
  });
});

Thank you

**Comment by justinmchase** [comment]
There is a middleware option also:
```
middleware: function (connect, opt) {
  return [ ... ]
}
```

**Comment by vapits** [comment]
@justinmchase Is there an example somewhere for that? I cannot find something. Just to change the default index file to another.

@vbabaria did you manage do this?
