### ISSUE TITLE
Provide ability to configure all options in tiny-lr

### ISSUE THREAD

**Issue by MeoMix** [AveVlad/gulp-connect#155]
Hey,

I've had to fork this repo so I can disable liveCSS and liveJs in tiny-lr. It would be nice if the options tiny-lr accepts could be passed down from gulp-connect.

**Comment by justinmchase** [comment]
The `lr` object is now exported on the root module. 

```
var connect = require('gulp-connect')
connect.lr
```

**Comment by MeoMix** [comment]
Sweet, thanks
