### ISSUE TITLE
Use HTTP/2 when https option is enabled

### ISSUE THREAD

**Issue by lyschoening** [AveVlad/gulp-connect#157]
Our project serves a lot of static files, so HTTP/2 would provide a significant performance improvement on reload.

It looks like it would be relatively straightforward to enable HTTP/2 support with the [http2](https://github.com/molnarg/node-http2) npm package. If the additional dependency is a concern, it could be made optional. Let me know if you would like a PR.

**Comment by bronzehedwick** [comment]
:+1: This is _exactly_ the feature I've been searching for!

**Comment by tomByrer** [comment]
I'd be interested to see what you have @lyschoening.

**Comment by justinmchase** [comment]
A PR would be welcome if you're still interested in this.
