### ISSUE TITLE
How to access demo.html by default instead of index.html

### ISSUE THREAD

**Issue by guohuihot** [AveVlad/gulp-connect#158]
http://localhost:8080
How to access demo.html by default instead of index.html

**Comment by justinmchase** [comment]
You can add middleware that routes `/` to `/demo.html`.

**Comment by Mousaka** [comment]
Do you need to use something like [gulp-connect-proxy](https://www.npmjs.com/package/gulp-connect-proxy) in the middleware in order to do this or can it be done with no extra libs? If the latter then how?
Cheers

**Comment by justinmchase** [comment]
I'm not actually sure. We are using it just to serve up a directory for use in local testing and so I haven't played around with all of the various connect features available. But basically `gulp-connect` is just a gulp wrapper around `connect` itself. So anything you can do with `connect` you can do with `gulp-connect`.
