### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by Shuliyey** [AveVlad/gulp-connect#161]
Is there any middleware or example to allow gulp-connect to support put request to upload a binary file

**Comment by justinmchase** [comment]
Here is the connect documentation:
https://www.npmjs.com/package/connect
```
gulp.task('connect', function() {
  connect.server({
    middleware: function(connect, opt) {
      function handlePut() {
        // todo...
      }
      return [handlePut]
    }
  });
});
```

**Comment by Shuliyey** [comment]
i see thanks @justinmchase , so I can basicly use **gulp-connect** the same way as I use **connect**?

**Comment by justinmchase** [comment]
Pretty much, it just wraps connect so it's gulp friendly.

**Comment by Shuliyey** [comment]
thank @justinmchase 

I got it working using route-connect :+1:

**Comment by justinmchase** [comment]
Thank @AveVlad, I just accept the PR's from time to time :smile:
