### ISSUE TITLE
Assets folder is accessible through url

### ISSUE THREAD

**Issue by paramsinghvc** [AveVlad/gulp-connect#162]
I want to forbid the assets folder access on being typed in the url directly. It shows up a directory structure right now. How can it be achieved?

**Comment by justinmchase** [comment]
You could probably do this with middleware
```
// Server and LiveReload
gulp.task('connect', function() {
    connect.server({
        middleware: function(connect, o) {
            function hideAssets() { .... }
            return [hideAssets];
        }
    })
});
```

You'll have to investigate `connect` documentation to see how to get the middleware to do this but I believe its possible.
