### ISSUE TITLE
Ignoring index.html

### ISSUE THREAD

**Issue by fegemo** [AveVlad/gulp-connect#163]
Hi. I've just updated to v3.0.0 and I noticed that it seems that connect started ignoring index.html inside folders, showing the directory listing instead of the html file.

Is this an intended change?

Thanks for the plugin!!

**Comment by SuneBear** [comment]
+1, I had the same problem : (

**Comment by erkobridee** [comment]
+1, same problem here with v3.0.0

**Comment by RyanWarner** [comment]
+1 same problem here

**Comment by EHLOVader** [comment]
Looks like https://github.com/AveVlad/gulp-connect/pull/160 is the cause of the problems. Lots of changes including the fallback option which defaults to undefined in there.

I tried setting the fallback to `index.html` but then I got stranger errors about the file not being found.

```
Error: ENOENT: no such file or directory, open 'index.html'
```

**Comment by red2678** [comment]
+1 Same here

**Comment by muzuiget** [comment]
Same here, even setting `fallback` option, still not work.

**Comment by syed-haroon** [comment]
+1  I have updated to  v3.0.1 but still have the same problem.

**Comment by stevenorell** [comment]
+1, same issue. Running 3.1.0, I just get a directory listing, even with the fallback set to the path to index.html. This is my task:

```
gulp.task('connect', function(){
  connect.server({
    fallback: './src/index.html',
    root: './src'
  });
});
```

**Comment by mafrost** [comment]
+1 Also having this problem

**Comment by bagwaa** [comment]
+1 same problem

**Comment by alessiodionisi** [comment]
+1 same problem

**Comment by britztopher** [comment]
+1 same problem as well

**Comment by simon-thorpe** [comment]
+1 here

**Comment by jornbakhuys** [comment]
+1 same problem

**Comment by OutThisLife** [comment]
+1

**Comment by adrianchung** [comment]
+1

**Comment by lusarz** [comment]
+1

**Comment by nerdybeast** [comment]
+1

**Comment by musamanyama** [comment]
Thank you euwest, hope this gets merged quickly :+1:

**Comment by blinkcat** [comment]
+1

**Comment by michaelryancaputo** [comment]
@blinkcat Github has reactions now :dancer:

**Comment by enlore** [comment]
+1

**Comment by samueledirito** [comment]
+1

**Comment by airwin** [comment]
+1024 :(

**Comment by red2678** [comment]
Problem solved! http://browsersync.io

**Comment by fegemo** [comment]
@red2678, I tried it as a replacement for gulp-connect and dropped it.

For my scenario, which is to use gulp-connect just to have livereloading during dev, using browsersync is like killing an ant with a bazooka - besides, it introduces some overhead, which hurts performance.

Last, it is not a nice thing to advertise other solutions in such a way when we are in open source world ;)

**Comment by jwhitmarsh** [comment]
+1+1

**Comment by s3bubble** [comment]
+++1

**Comment by 59naga** [comment]
my solved case:
```js
  connect.server({
    livereload: {
      include: [/^(?!.*index\.html)*$/]
    }
  })
```

**Comment by 59naga** [comment]
solved my case(required remove cache):
```js
  connect.server({
    livereload: {
      include: [/^\/.+?$/]
    }
  })
```

**Comment by vangorra** [comment]
I found setting the path to fallback to an absolute path works great.

``` javascript
  connect.server({
    root: path.resolve(path.join(__dirname, 'dist/app')),
    livereload: false,
    host: '0.0.0.0',
    port: 8000,
    fallback: path.resolve('./dist/app/index.html')
  });
```

**Comment by fygethub** [comment]
@vangorra  Thanks,It works when I replace the fallback to an absolute path
