### ISSUE TITLE
Livereload is broken since 3.0.0

### ISSUE THREAD

**Issue by pakro** [AveVlad/gulp-connect#165]
I can't get the live reloading to work.
Somehow LiveReload.prototype.performReload is not called in the latest build.
I downgraded the version to 2.3.1 and everything works fine.

**Comment by LamaZyrtex** [comment]
This I may confirm, too.

**Comment by webraptor** [comment]
The livereload script `<script type="text/javascript" src="http://localhost:35729/livereload.js?snipver=1"></script>` isn't injected into the HTML any longer?

**Comment by webraptor** [comment]
This was my first try and the html was actually blank, without any tags. Looked into the inject code and realised it was looking to inject into a proper html file. Added a basic html structure to index.html and everything's fine now.

**Comment by pakro** [comment]
@webraptor is your stuff properly reloading. For me this was not the case despite the fact that the livereload.js was injected correctly into my index.html.

**Comment by webraptor** [comment]
@pakro yes it is reloading fine.

**Comment by pakro** [comment]
@webraptor well thanks... then I made a fault somehow. Will look into it. Thanks for confirming that it is working. If @LamaZyrtex could solve his issues, this issue can be closed.

**Comment by pakro** [comment]
@webraptor Just tried it again. For me it does not work... First issue it never loads the index.html. Second issue it just does not reload. Could you share the tasks where you call connect() and reload()?

**Comment by webraptor** [comment]
`gulp.task('watch', () => {
  gulp.watch(['./src/*'], () => {   
    gulp.src('./src/**/*').pipe(connect.reload());
  });
});

gulp.task('webserver', ['watch'], () => {     
  gulp.src('./src/index.html')
    .pipe(open({ uri: 'http://localhost:8080/index.html', app: 'firefox' }));
  connect.server({   
    root: 'src',
    livereload: true
  });
});`

The src structure is:
/index.html
/app.js
/modules/*

I'll be using ES2015 for the project.

**Comment by pakro** [comment]
Thank you @webraptor! I will look into this and try to figure out why it is not working for me.

**Comment by syed-haroon** [comment]
+1  I have updated to  v3.0.1 but still have the same problem.

**Comment by Ice32** [comment]
I'm having the same problem, chrome browser wouldn't reload in the newest version 3.1.0. Downgrading to 2.3.1 as the person above said solved it

**Comment by pakro** [comment]
@Ice32 I also used chrome for my testing. Didn't test it on Firefox. Maybe thats the issue. @webraptor Sorry for bothering you again... which browser do you use? Which operating system you all use? I'm using Ubuntu.

**Comment by joshlangner** [comment]
+1. Just tried 3.1 and livereload fails to refresh the browser. Spent hours troubleshooting to no avail. Finally downgraded to 2.2 and it worked. There's a definite issue with 3+.

**Comment by minhyeong-kim** [comment]
me too

**Comment by ryan10328** [comment]
I face the same problem, and the version of my gulp-connect is 3.1.0

**Comment by britztopher** [comment]
+1 same issue here as well

**Comment by simon-thorpe** [comment]
Same issue here for v3.1.0.

Doing a test on css editing it seems to be ws://localhost:35729/livereload doesn't send the reload events to the client when modified. It does do this however on v2.3.1 which worked.

**Comment by michelecocuccio** [comment]
Same problem. File injected successfully at the bottom of the HTML page but not reloading :(

**Comment by hrenly** [comment]
> Same issue here for v3.1.0.
> Doing a test on css editing it seems to be ws://localhost:35729/livereload doesn't send the reload events to the client when modified. It does do this however on v2.3.1 which worked.
++
Mac, Chrome 48
Gulp-connect 3.1.0 Don't work
Gulp-connect 2.3.1 All ok

**Comment by juliandoucette** [comment]
Same issue.

1. Script is injected and doesn't throw any errors.
2. gulp logs reload on change
3. page doesn't reload

Works when downgraded to 2.3.1

**Comment by PKuebler** [comment]
Same issue.

**Comment by chenfengjw163** [comment]
Same issue

**Comment by ethancfchen** [comment]
Same issue here

**Comment by pakro** [comment]
I'll try to analyze the issue this weekend. But don't expect too much. I'm very unfamiliar with CoffeeScript.

**Comment by sterjakovigor** [comment]
Same issue!

**Comment by stasnobody** [comment]
Livereload not working.
test:
gulp-connect 3.1.0,
newest chrome/firefox, win 10 / arch linux

> Script is injected and doesn't throw any errors.
gulp logs reload on change
page doesn't reload

**Comment by yuluhuang** [comment]
i do not resolve but i use Chrome Extension  livereload to refresh  is ok

**Comment by LamaZyrtex** [comment]
3.1.1: Refresh seem to be working again on my side. I thank you for the good work you have put in. I hope to contribute at a later stage. (Btw: I have chosen to stay on the old 2.3.1 until now, which worked for me).

Env: Newest chrome, win10.

**Comment by justinmchase** [comment]
Sorry everyone, apparently I wasn't subscribed to new messages in this project :(

There was an issue with the middleware, Can you try it now and see if the bug is reproducible?

**Comment by pakro** [comment]
Thank you so much for fixing this!
