### ISSUE TITLE
Restrict access from outside localhost

### ISSUE THREAD

**Issue by mafrost** [AveVlad/gulp-connect#167]
How would I go about restricting access to the server from outside of localhost? Normally for grunt-connect and similar "plugins" the default is to not allow outside access. To allow it, I would set host:'0.0.0.0' or similar. Is this possible here?

**Comment by justinmchase** [comment]
On the options object there is a `options.host` option which defaults to `localhost`. I think that should actually already use the loopback adapter and access from outside should be restricted. You could specifically specify `127.0.0.1`. Using `0.0.0.0` would open the port on all adapters and allow access from the outside.
