### ISSUE TITLE
Empty page when using compression and livereload

### ISSUE THREAD

**Issue by galtalmor** [AveVlad/gulp-connect#179]
In latest gulp-connect (version 3.2.2), when I use [Compression](https://www.npmjs.com/package/compression) and set `livereload: true` any page is returned as blank.

This is my task:

```
connect.server({
        root: [__dirname + '/' + BUILD_DIR],
        port: 8080,
        livereload: true,
        middleware: function () {
            return [
                compression({})
            ];
        }
    });
```

When I set `livereload: false` or remove `compression({})` it works fine.

The exact code works just fine with gulp-connect 2.3.1 .
Thanks.

**Comment by justinmchase** [comment]
I don't know the answer to this one, PR's welcome.

**Comment by c1aphas** [comment]
Same here. All was fine, but when i added 1 new line to one of my jade templates - i got blank page. 
If i disable compression all works fine.

**Comment by justinmchase** [comment]
Could one of you guys make a minimal repro that will allow me to see the error by doing:
```
$ cd bug179
$ npm install
$ gulp
```

If I can do that and see the issue I may be able to figure out the problem for you.

**Comment by muzuiget** [comment]
@justinmchase here the demo file can reproduce the bug

[bug179.zip](https://github.com/AveVlad/gulp-connect/files/253320/bug179.zip)

**Comment by muzuiget** [comment]
I seem to found what cause this bug, it is livereload can't inject it's js code to the html, after ignore the html file in compression, then everything works.

their are workaround code

```
compression({
    filter: (req) => {
        return req.url !== '/';
    },
});
```

So I think gulp-connect v3 resort the user middlewares order in connect server.

**Comment by justinmchase** [comment]
I've been busy but I'll check it out. There was a fix recently related to the ordering of middleware, which may be the culprit. It could be that that fix wasn't quite right.

**Comment by chhaymenghong** [comment]
@galtalmor 
I had the same issue with grunt. It might be the same with Gulp. Here is how I fixed it.
- get rid of livereload
- install the livereload module. In my case: npm install connect-livereload --save-dev. This is what grunt-contrib-connect uses for "livereload".
- add middlewares in the following order:
`middleware: function (connect, options, middlewares) {
            middlewares.unshift(compression(), require('connect-livereload')())
            return middlewares;
          }`


If you are not using a proxy, you can get rid of the "grunt-middleware-proxy" middleware.

**Comment by galtalmor** [comment]
@chhaymenghong 
Thanks for the reply.
I do not work on this project anymore, so I can't confirm if the solution is working or not, but I hope it would help anyone who's having the same issue.

**Comment by justinmchase** [comment]
If this is still relevant please submit a PR, I don't have the bandwidth to check it out or make a fix. I'm closing for now since its stale but if you make a PR and link this ticket I'll re-open it.
