### ISSUE TITLE
Load changed sass without refreshing browser

### ISSUE THREAD

**Issue by chrleon** [AveVlad/gulp-connect#184]
Can I get this to inject just the changed css into devtools insted of reloading the entire page?

Using it for developing responsive banners and I have a page with 7 iframes that I would love to not refresh every time i do a change in the scss-file. I want to inject only the css into Chrome.

Is there example gulptasks that would let me do that?

**Comment by justinmchase** [comment]
this isn't really going to do that, live-reload may have that capability though I'm not sure.
