### ISSUE TITLE
Using https causes memory leak

### ISSUE THREAD

**Issue by bethany-dawn** [AveVlad/gulp-connect#186]
When setting https to true, I get the following error:

(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by justinmchase** [comment]
Can you show a snippet of your watch code?

**Comment by bethany-dawn** [comment]
gulp.watch(app.paths.images, ['images']);
gulp.watch(app.paths.js, ['js']);
gulp.watch(app.paths.rjs, ['browserify']);
gulp.watch(app.paths.scss, ['scss']);
gulp.watch(app.paths.copy, ['copy']);
gulp.watch(app.paths.html, ['preprocess']);

browserify.instance.on('update', browserify.bundle);

This error happens even with all watches commented out.

**Comment by justinmchase** [comment]
How about your whole gulpfile? Or at least the part where `gulp-connect` is used because in general others are using https but not having this issue.

**Comment by bethany-dawn** [comment]
Connect task is below:

gulp.task('connect', function() {
  connect.server({
    root: 'dist',
    fallback: 'dist/index.html',
    host: 'host.com'
  });
});

**Comment by justinmchase** [comment]
That looks pretty straight forward :-/

If you can send a simple zip file which will allow me to:
```
$ cd bug-186
$ npm install
$ gulp
```

And reproduce the issue I could probably help you.
