### ISSUE TITLE
livereload does not work with Angular2 component styleUrls

### ISSUE THREAD

**Issue by nixegend** [AveVlad/gulp-connect#189]
@Component({
  selector: 'ng2-app',
  templateUrl: 'app/main.html',
  **styleUrls: ['app/main.css']**
})

it seems like 'livereload' script does not see these files

**Comment by justinmchase** [comment]
We're using `tiny-rl` and `connect-livereload`, can you push this bug over to them?

```
liveReload = require("connect-livereload")
tiny_lr = require("tiny-lr")
```

**Comment by nixegend** [comment]
Thanks for the reply, I forwarded this bug to them.

2016-06-06 17:03 GMT+03:00 Justin Chase <notifications@github.com>:
