### ISSUE TITLE
Livereload shadow dom web components

### ISSUE THREAD

**Issue by kmturley** [AveVlad/gulp-connect#190]
I have a simple web component demo, with a single component containing html, css and js. I would like to reload the exact asset when it changes (NOT the entire page).

    gulp.task('watch', function () {
        gulp.watch(['/**/*.css'], function (event) { console.log('css', event.path); gulp.src(event.path).pipe(connect.reload()); });
        gulp.watch(['/**/*.html'], function (event) { gulp.src(event.path).pipe(connect.reload()); });
        gulp.watch(['/**/*.js'], function (event) { gulp.src(event.path).pipe(connect.reload()); });
    });

When I modify any html/js files they are updated automatically via livereload and it works! EVEN if the html or js is INSIDE the web component e.g.

    <link href="header-custom.css" rel="stylesheet" />
    <template>
        <p>Hello <strong></strong></p>
    </template>
    <script src="header-custom.js"></script>

However when updating css files inside the same webcomponent it does not livereload :( The event does fire correctly, so watch is detecting the file has changed, and the correct path:

    css /web-components/src/components/header-custom/header-custom.css

I'm guessing the issue might be because the css is extracted from the web components and placed into the head of the document? This is how the page is rendered after a web component is loaded:

![screen shot 2016-06-08 at 11 19 24 am](https://cloud.githubusercontent.com/assets/1710493/15899805/f7fc91f4-2d6a-11e6-8dff-132c5442e596.png)

I believe it's a bug, or an unsupported feature, which just happens to work for html/js but not css!

Full source code is here:
https://github.com/kmturley/web-components

Demo:
http://kmturley.github.io/web-components/src/

**Comment by justinmchase** [comment]
Live reload is a different project you may want to push this over to them.

**Comment by kmturley** [comment]
Ok that's a better idea, closing this and opened a new issue at:
https://github.com/intesso/connect-livereload/issues/72
