### ISSUE TITLE
connect.reload() is not working

### ISSUE THREAD

**Issue by ttson24** [AveVlad/gulp-connect#196]
i have to config  gulp. in window is run ok, but mac os 10.11.5 is not run
when i change content of html file. command line (gulp) is run but content in browser is not changed.

could you help me, plz!!
[Directive.zip](https://github.com/AveVlad/gulp-connect/files/355051/Directive.zip)

**Comment by regisbsb** [comment]
same here

**Comment by justinmchase** [comment]
Do you have code samples or a way to reproduce the bug?

**Comment by pgore** [comment]
[Archive.zip](https://github.com/AveVlad/gulp-connect/files/364272/Archive.zip)

I have been following a tutorial on pluralsite. The problem I am having is that the connect-reload is not working; the webpage does not update when I save the file. I have to manually refresh the page. The Javascript which is meant to be injected onto the page does not appear. Nothing online seems to offer a solution. I am using a mac machine.

**Comment by mpmlj** [comment]
same

**Comment by justinmchase** [comment]
@ttson24 Your example works for me. I just did:

```
$ npm install
$ gulp
```

Then in my browser I went to http://localhost:9000, enabled LiveReload in Chrome.

Then I went to `build/development/view/index.html` and changed it slightly. It immediately reloaded the page in chrome.

**Comment by justinmchase** [comment]
I have LiveReload version `2.1.0` installed. I am using Chrome. I am currently testing this on Windows 10.

Ensure that your firewall or anti-virus is not blocking the livereload port. Also, I received this error message when running `gulp`:

```
[11:17:12] { [Error: You need to have Ruby and Compass installed and in your system PATH for this task to work.]
  message: 'You need to have Ruby and Compass installed and in your system PATH for this task to work.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function: bound ] } }
```

It's possible that something in that gulp task (which is not running for me) is actually causing problems for you.

Another possibility is that you are running live reload servers multiple times. Meaning, if some other process is also holding open the LR port then it may cause this to silently fail.

**Comment by SagarNenwani** [comment]
Solved the problem for me using following steps
1. Install gulp globally for the first time using 
  npm install -g gulp
2. Download a Live reload extension for chrome
3. Make sure not using any reserved ports or port 35729(reserved for livereload)
