### ISSUE TITLE
Can the server send a 404 if the fallback fails?

### ISSUE THREAD

**Issue by bjmiller** [avevlad/gulp-connect#200]
Right now, my build process throws errors if it tries to fall back to a file that doesn't exist.  Can we set the fallback to send a proper 404 if the file it tries to send doesn't exist?

Currently, the fallback just naively assumes that the file by that name exists, and tries to create a read stream out of it.

**Comment by justinmchase** [comment]
You can do it with middleware:

https://github.com/AveVlad/gulp-connect/issues/9
