### ISSUE TITLE
Livereload doesn't work in Firefox

### ISSUE THREAD

**Issue by byrnane** [avevlad/gulp-connect#207]
Livereload doesn't work in Firefox
I fully followed the tutorial
Just nothing happens when i'm changing my files

_Require:_

``` JS
connect = require('gulp-connect');
```

_Example task:_

``` JS
gulp.task('buildLayouts', function() {
    return gulp.src(path.src.html)
        .pipe(pug({
            pretty: true,
        }))
        .pipe(gulp.dest(path.build.html))
        .pipe(connect.reload())
        .on('error', function(error) {
            console.error('' + error);
        });
});
```

_Serve task:_

``` JS
gulp.task('serve', function() {
    connect.server({
        root: 'build',
        livereload: true,
        name: 'Webserver',
    });
});
```

_And default task:_

``` JS
gulp.task('default', ['build', 'serve',  'watch']);
```

**Comment by justinmchase** [comment]
You have the live reload plugin running in firefox?

**Comment by byrnane** [comment]
Yep, plugin is installed and turned on

**Comment by justinmchase** [comment]
Does it work when you use chrome? Are there any errors? Did you check that your firewall isn't blocking the port? Are you sure its configured to use the same port both places?

**Comment by byrnane** [comment]
No, it doesn't work in chrome too, lol... Port is open, firewall is turned off. What do you mean about "both places"?

**Comment by byrnane** [comment]
Is it right plugin: [livereload](http://livereload.com/)?

**Comment by byrnane** [comment]
![gulp](https://cloud.githubusercontent.com/assets/12965194/18807283/2e0c652e-826d-11e6-8eff-8162009a1792.png)

**Comment by byrnane** [comment]
Lol, now it works. I just added a couple of new template files, and livereload was triggered. I have no words...
