### ISSUE TITLE
open: { browser: 'Google Chrome'} error!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [AveVlad/gulp-connect#209]
> open: { browser: 'Google Chrome'}

![open-error](https://cloud.githubusercontent.com/assets/18028768/19084351/cc576d40-8a98-11e6-9c8c-e21309a89fa3.PNG)

**Comment by xgqfrms-GitHub** [comment]
![gulp-error](https://cloud.githubusercontent.com/assets/18028768/19084259/69b3e01a-8a98-11e6-9567-eff7e25575ca.PNG)
![gulp-task-error](https://cloud.githubusercontent.com/assets/18028768/19084260/69bd173e-8a98-11e6-80d5-2c9fbc1c33ae.PNG)

**Comment by justinmchase** [comment]
Tasks should either be an array of strings or a function. You are calling `connect.server` and passing the return value of that function in as a task which will end up being either an object or undefined I can't remember. Both of which are invalid tasks.

So turn this:
```
gulp.task('connect', connect.server(...
```
into:
```
gulp.task('connect', () => {
  connect.server(...)
})
```

**Comment by xgqfrms-GitHub** [comment]
Thanks a lot!
