### ISSUE TITLE
livereload not working 

### ISSUE THREAD

**Issue by l2trace** [AveVlad/gulp-connect#215]
I am not quite sure if this is a bug or my unfamiliarity of gulp-connect . live reload never refreshes when I run gulp watch. The sass task runs and finishes but there is no reload. I an am not seeing any events written to the ws in the browser other than the initial web socket connection. 

here is my gulp file https://gist.github.com/l2trace/4583dbdd5418b44d60c62f758eec0513
here is my package.json https://gist.github.com/l2trace/3c91623e3878b0d251bb40fd061b3fdc

**Comment by MadaoChen** [comment]
how did you fixed it？
