### ISSUE TITLE
https does not work with node 8.8

### ISSUE THREAD

**Issue by nicolashenry** [AveVlad/gulp-connect#236]
Since node 8.8 provide 'http2' module by default, `https` options does not work anymore.
It seems that the createServer is called instead of [createSecuredServer](https://nodejs.org/api/http2.html#http2_http2_createsecureserver_options_onrequesthandler) so the server is not responding correctly.

As a workaround, I use the environment variable `NODE_NO_HTTP2=1` in order to disable the new http2 module.

**Comment by binarykitchen** [comment]
have the same problem here - @nicolashenry how are you setting that environment variable?

**Comment by nicolashenry** [comment]
Like this in a bash terminal:
```bash
NODE_NO_HTTP2=1 gulp mytask
```
You also can set it for your whole terminal session with:
```bash
export NODE_NO_HTTP2=1
```
Or like this if you are using a windows terminal:
```bat
set NODE_NO_HTTP2=1
```

**Comment by binarykitchen** [comment]
right, thanks - works. hope this gets fixed in gulp-connect soon
