### ISSUE TITLE
It seems that release 5.1.0 in npm registry lack index.js

### ISSUE THREAD

**Issue by xiechao06** [AveVlad/gulp-connect#241]
Since there's no "index.js"

```javascript
const connect = require('gulp-connect');
```
complains module 'gulp-connect' can't be found

**Comment by johnnynode** [comment]
@xiechao06 check README.md

```
To contribute to this project, you must have CoffeeScript installed: npm install -g coffee-script.

Then, to build the index.js file, run coffee -o . -bc src/. Run npm test to run the tests.
```

**Comment by xiechao06** [comment]
@johnnynode thanks for your response, instead I retreat to use version 5.0.0.
You provide a workaround, but I think this is still a problem. eg. if I could just install gulp-connect@5.0.0 and get everything done, but why in this same major version (5.1.0), I need to do this extra step in script or something?

**Comment by emismith90** [comment]
This is how I fix for our project: 
- Add  "coffee-script": "^1.12.7" to devDependencies
- Define "build-gulp-connect" task:
```
"scripts": {
    "start": "node index.js",
    "build": "gulp build",
    "build-gulp-connect": "coffee --compile --output node_modules/gulp-connect/ node_modules/gulp-connect/src/",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

- Add additional step before your automation build (if necessary)

**Comment by LinBoLen** [comment]
pls fix it

**Comment by johnnynode** [comment]
@xiechao06 yeah, just a workaround.

**Comment by Kyrodan** [comment]
The *NPM*-Package is broken - as @xiechao06 stated. The NPM-Package is currently unusable and the version 5.1.0 should be revoked from NPM. A new version (e.g. 5.1.1) containing compiled `index.js` should be provided quickly.

**Comment by SeanHub** [comment]
Yeah my Jenkins server is failing my builds because of the "Cannot find module 'gulp-connect'" error.

**Comment by meibegger** [comment]
+1

**Comment by 2016caicai** [comment]
+1， I mistaken that my NPM is bad

**Comment by geryit** [comment]
had to revert to 4.2 : `"gulp-connect": "^4.2.0",`

**Comment by battlemidget** [comment]
We are pinned at 5.0.0 but the same issue still occurs

**Comment by AveVlad** [comment]
Please update to gulp-connect@5.2.0

![image](https://user-images.githubusercontent.com/2889662/34545278-f46eec4c-f0fc-11e7-8c7b-39ef9b200440.png)
