### ISSUE TITLE
Address event-stream 3.3.6 malware

### ISSUE THREAD

**Issue by milesflo** [AveVlad/gulp-connect#260]
Your project has a malicious package.
```
├─┬ gulp-connect@5.5.0
│ └─┬ event-stream@3.3.6 
│   └── flatmap-stream@0.1.0 
```

More info:
https://github.com/dominictarr/event-stream/issues/116

**Comment by bkrrrr** [comment]
update to event-stream 4.0.0 should do it:
https://github.com/dominictarr/event-stream/issues/115#issuecomment-442053125
