### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by wclr** [AveVlad/gulp-connect#27]
Do you plan add proxy support (like grunt-connect-proxy) or maybe develop separate module?

**Comment by saadfarooq** [comment]
Any news on websocket support ?

**Comment by davinkevin** [comment]
+1, it's a problem to not be able to proxy Web-Socket in gulp-connect.

**Comment by rusintez** [comment]
@saadfarooq @davinkevin 
There is a public fork  + examples https://github.com/seedalpha/gulp-connect#optionsplugins of plugin architecture that exposes `server`, so you could easily attach to it.

**Comment by rusintez** [comment]
There's also a pending pr https://github.com/AveVlad/gulp-connect/pull/92 to add this

**Comment by chimurai** [comment]
@vincentbernat @saadfarooq  @davinkevin 

You might want to checkout [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware). Its features should be on par with grunt-connect-proxy and it supports websockets as well.

Example:
```javascript
var gulp = require('gulp');
var connect = require('gulp-connect');
var proxy = require('http-proxy-middleware');

gulp.task('connect', function() {
    connect.server({
        root: ['./app'],
        middleware: function(connect, opt) {
            return [
                proxy('/socket', {
                    target: 'http://localhost:3000'
                    changeOrigin:true,
                    ws: true      // <-- set it to 'true' to proxy WebSockets
                })
            ]
        }

    });
});

gulp.task('default', ['connect']);
```
