### ISSUE TITLE
Readme usecases do not show how to support multiple connect tasks

### ISSUE THREAD

**Issue by smysnk** [AveVlad/gulp-connect#32]
I was trying to create different connect tasks for develop / production testing.  Using gulp-connect as the documentation suggests:

```
gulp.task('connect', connect.server({root:'src'}));
gulp.task('connect-dist', connect.server({root:'dist'}));
```

Executing the 'connect' task will have connect serve the 'dist' folder instead of intended 'src'.  My solution to this was to do this instead:

```
gulp.task('connect', function() {
    connect.server({root:'src'})();
});
gulp.task('connect-dist', function() {
    connect.server({root:'dist'})();
});
```

Maybe documentation should show how to run multiple configurations possibly?

**Comment by KaoruDev** [comment]
i'm just as confused. I'm trying to mount `./projects/app/dist` along with `./node_modules`.

i realize i could start up another connect instance and have it listen to a different port, but i rather have it all come through the same port, not sure if that's doable.
