### ISSUE TITLE
Error: Forbidden send.js

### ISSUE THREAD

**Issue by hueitan** [AveVlad/gulp-connect#38]
Heading this problem on current version.

https://github.com/visionmedia/express/issues/1229

**Comment by gooofly** [comment]
@doomsbuster  I fixed the issue as you. thank you very much!

**Comment by kunegun** [comment]
It works for me too! thx

**Comment by ciscoo** [comment]
@doomsbuster also worked for me, thanks!

**Comment by wikieswan** [comment]
@doomsbuster  thx,it helps me!~
