### ISSUE TITLE
Single reload

### ISSUE THREAD

**Issue by sshmyg** [AveVlad/gulp-connect#71]
Hey.
Is it possible refresh page only once, if I build a lot of files?
e.g. Build all dependencies of jade file, and now it refresh page for every builded file.

**Comment by Christo44** [comment]
I know it's closed up using something like gulp-changed helped me a lot, but there is still the problem that where one has a included file (footer) and it's edited, I don't get a refresh without saving the parent (index). 

I.e
index.jade
|-- include footer
