### ISSUE TITLE
connect.serverClose() leaves livereload up

### ISSUE THREAD

**Issue by mickeyvip** [AveVlad/gulp-connect#81]
Hi,

I am running local protractor (selenium) tests, where I am starting the webserver with `livereload`, then run  the protractor, then I want to stop the webserver:
```javascript
gulp.task("build", function (cb) {
  runSequence(
      ["build-js", "build-less", "build-templates"],
      "build-html",
      cb);
});

gulp.task("run-server", false, function () {
  return connect.server({
    root: '../app',
    port: 9090,
    livereload: true,
    fallback: '../app/index.html'
  });
});

gulp.task('test-e2e-local', function (cb) {
  runSequence("build", "run-server", function() {
    return gulp.src(["./test/e2e/**/*.js"])
    .pipe(protractor({
      configFile: "./test/e2e/config/protractor.conf.js",
      args: ['--chromeDriver', chromeDriverPath,
        '--seleniumServerJar', seleniumServerPath,
        '--baseUrl', baseUrl]
    }))
    .on('error', function (e) {
      throw e;
    })
    .on('end', function() {
      connect.serverClose();
    });
    return cb();
  });
});
```

It seems that the webserver is stopping but the terminal hangs on `server stopped` and I see that the `livereload` is still up (`node` process is running on the port).

**Comment by kmpm** [comment]
Happens to me to...

**Comment by kmpm** [comment]
Is this fixed, or is it not a bug at all? 
And if it is fixed, is it published in npm?

**Comment by vyscond** [comment]
This issue should be reopened. Still happens to me

**Comment by seedy** [comment]
This bug still happens to me 2 years after.
I see no solution provided, nor  any explanation from @AveVlad  since he closed it.
Could you reopen it please?
