### ISSUE TITLE
Livereload doesnt reload the browser #62 (Duplicate)

### ISSUE THREAD

**Issue by mcneela86** [AveVlad/gulp-connect#88]
I am duplicating this issue as there was no solution flagged: https://github.com/AveVlad/gulp-connect/issues/62

I am having an issue with the browser not reloading, the change is being picked-up and I can see it in the terminal - it just won't update the browser.

I am using the sample code for 'LiveReload': https://www.npmjs.org/package/gulp-connect#livereload

**Comment by alvint** [comment]
I had a similar issue. If' you're using HTTPS, you need to permanently trust the (unsigned) certificate that gulp-connect uses. Or you can use HTTP.

Hope this helps,
Alvin

**Comment by bfunc** [comment]
in my case it sometimes stop working, windows restart helps
