### ISSUE TITLE
gulp crashes when fallback is specified and the page is not found

### ISSUE THREAD

**Issue by alvint** [AveVlad/gulp-connect#93]
1. Specify a fallback, for example "index.html".

2. In the browser, navigate to a URL that doesn't exist, for example "localhost:8000/foo". Instead of simply displaying "Cannot GET /foo" in the browser (correct behavior), the gulp process crashes with the following error:

```
[16:10:36] Server started http://localhost:8000
[16:10:36] LiveReload started on port 35729

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'index.html'

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.14
npm ERR! code ELIFECYCLE
npm ERR! ktoi@0.1.0 start: `gulp`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ktoi@0.1.0 start script 'gulp'.
npm ERR! This is most likely a problem with the ktoi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls ktoi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alvin/Dev/projects/dbs/ktoi/npm-debug.log
```

No additional useful information is in `npm-debug.log`.

**Comment by stevenpetryk** [comment]
:+1:

**Comment by slavafomin** [comment]
:+1:

**Comment by ccnokes** [comment]
+1
Related to this: if you're running a SPA and you include a script that is not in root folder, the server will send the fallback HTML file instead of 404ing, which then causes some confusing errors because the browser attempts to parse HTML as JS. I wrote a middleware function to get around this, but it's breaking the livereload functionality.

**Comment by slavafomin** [comment]
@ccnokes I've created a small package to run SPA applications:
https://github.com/betsol/spa-server
Maybe it will be usable to you.
I'm using it instead of `gulp-connect` and `gulp-webserver` cause they are both broken.

**Comment by ccnokes** [comment]
@slavafomin From your docs, it looks like it would have the same issue: "However, when missing URL is requested it returns resource from fallback URL (e.g. /index.html)". So if the server attempts to serve a missing JS file, it serves an HTML file instead of 404ing.

**Comment by slavafomin** [comment]
@ccnokes I think I will be able to provide a fix for this issue. Could you please create an issue in my repo with description of desired behavior? I will try to implement it. I was planing to do this anyway ;)

**Comment by ccnokes** [comment]
@slavafomin Awesome, will do. Yeah, it doesn't seem like to difficult of a fix.

**Comment by stevenpetryk** [comment]
One good technique is this (psuedocode):

```
if request_type == 'text/html' && resource_not_found
  serve fallback
else
  404
```

Since browsers request text/html for the initial page request.

**Comment by slavafomin** [comment]
@stevenpetryk thank you for your suggestion, I think investigating the `Accept` HTTP header would be a pretty solid approach. I will try to implement it in my project and will post a real code snippet here if @AveVlad would like to use it.

**Comment by vangorra** [comment]
I found setting the path to fallback to an absolute path works great.

``` javascript
  connect.server({
    root: path.resolve(path.join(__dirname, 'dist/app')),
    livereload: false,
    host: '0.0.0.0',
    port: 8000,
    fallback: path.resolve('./dist/app/index.html')
  });
```
